# Generated by Django 6.0.1 on 2026-02-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='NEW', max_length=20),
        ),
    ]
